name: Spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crystal:
          - latest
          - 1.16.3
          - 1.15.1
          - 1.14.1

    container:
      image: crystallang/crystal:${{ matrix.crystal }}

    steps:
    - uses: actions/checkout@v4
    - name: Install unzip
      run: apt-get update && apt-get install -y unzip
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Install dependencies and build codegen
      run: shards build
    - name: Run crystal spec
      run: make spec
